# Generated by Django 3.0.8 on 2020-08-20 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0005_auto_20200820_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_things', through='ads.Fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
